apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: e2e-tests-cluster-agent
spec:
  serviceAccountName: e2e-tests-pipeline
  triggers:
    - bindings:
        - kind: ClusterTriggerBinding
          ref: github-push
      template:
        ref: gitops-service-cluster-agent
